### ISSUE TITLE
Consider renaming the library feature

### ISSUE THREAD

**Issue by nicolaslara** [CosmWasm/cw-template#140]
Using the word "library" for the feature to determine if the contract is being imported is confusing (especially now that all contracts should be compiled with `--lib`). 

I propose renaming the default feature in this template to "imported". That way new contracts can specify `#[cfg_attr(not(feature = "imported"), entry_point)]`, which I think is much easier to read/understand for newcommers

**Comment by webmaster128** [comment]
While we are here, what about inverting the flag to make it additive in the sense Rust features are supposed to work. If we change "library" -> "entry_points" and only compile the entry points if that feature is set, we get even more clarity IMO.

In order to avoid issues with Wasm build tooling, "entry_points" needs to be a default feature. To deactivate it, a user has to use something like

```diff
-cw1-whitelist = { version = "0.16.0", features = ["library"] }
+cw1-whitelist = { version = "0.16.0", default-features = false }

 # or

-cw1-whitelist = { version = "0.16.0", features = ["library", "test-utils"] }
+cw1-whitelist = { version = "0.16.0", default-features = false, features = ["test-utils"] }
```

**Comment by webmaster128** [comment]
Closing in favour of https://github.com/CosmWasm/cosmwasm/issues/1627
